name = "remix-cloudflare-template"
compatibility_date = "2024-02-11"
pages_build_output_dir = "build"
kv_namespaces = [
  { binding = "cache", id = "cache" }
]

[vars]
GITHUB_OWNER = "edmundhung"
GITHUB_REPO = "remix-cloudflare-template"
